// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.15.6
// source: api/router/v1/service.proto

package v1

import (
	errors "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	v1 "xhappen/api/protocol/v1"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeviceInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientID       string        `protobuf:"bytes,1,opt,name=clientID,proto3" json:"clientID,omitempty"`
	ServerID       string        `protobuf:"bytes,2,opt,name=serverID,proto3" json:"serverID,omitempty"`
	ConnectSequece uint64        `protobuf:"varint,3,opt,name=connectSequece,proto3" json:"connectSequece,omitempty"`
	CurVersion     int32         `protobuf:"varint,4,opt,name=curVersion,proto3" json:"curVersion,omitempty"`
	DeviceType     v1.DeviceType `protobuf:"varint,5,opt,name=deviceType,proto3,enum=protocol.v1.DeviceType" json:"deviceType,omitempty"`
}

func (x *DeviceInfo) Reset() {
	*x = DeviceInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_router_v1_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfo) ProtoMessage() {}

func (x *DeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_router_v1_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfo.ProtoReflect.Descriptor instead.
func (*DeviceInfo) Descriptor() ([]byte, []int) {
	return file_api_router_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *DeviceInfo) GetClientID() string {
	if x != nil {
		return x.ClientID
	}
	return ""
}

func (x *DeviceInfo) GetServerID() string {
	if x != nil {
		return x.ServerID
	}
	return ""
}

func (x *DeviceInfo) GetConnectSequece() uint64 {
	if x != nil {
		return x.ConnectSequece
	}
	return 0
}

func (x *DeviceInfo) GetCurVersion() int32 {
	if x != nil {
		return x.CurVersion
	}
	return 0
}

func (x *DeviceInfo) GetDeviceType() v1.DeviceType {
	if x != nil {
		return x.DeviceType
	}
	return v1.DeviceType(0)
}

type DeviceBindRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceInfo *DeviceInfo `protobuf:"bytes,1,opt,name=deviceInfo,proto3" json:"deviceInfo,omitempty"`
}

func (x *DeviceBindRequest) Reset() {
	*x = DeviceBindRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_router_v1_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceBindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceBindRequest) ProtoMessage() {}

func (x *DeviceBindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_router_v1_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceBindRequest.ProtoReflect.Descriptor instead.
func (*DeviceBindRequest) Descriptor() ([]byte, []int) {
	return file_api_router_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *DeviceBindRequest) GetDeviceInfo() *DeviceInfo {
	if x != nil {
		return x.DeviceInfo
	}
	return nil
}

type DeviceBindReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret   bool           `protobuf:"varint,1,opt,name=ret,proto3" json:"ret,omitempty"`
	Exist *DeviceInfo    `protobuf:"bytes,2,opt,name=exist,proto3" json:"exist,omitempty"`
	Err   *errors.Status `protobuf:"bytes,3,opt,name=err,proto3" json:"err,omitempty"` //kratos通用错误
}

func (x *DeviceBindReply) Reset() {
	*x = DeviceBindReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_router_v1_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceBindReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceBindReply) ProtoMessage() {}

func (x *DeviceBindReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_router_v1_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceBindReply.ProtoReflect.Descriptor instead.
func (*DeviceBindReply) Descriptor() ([]byte, []int) {
	return file_api_router_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *DeviceBindReply) GetRet() bool {
	if x != nil {
		return x.Ret
	}
	return false
}

func (x *DeviceBindReply) GetExist() *DeviceInfo {
	if x != nil {
		return x.Exist
	}
	return nil
}

func (x *DeviceBindReply) GetErr() *errors.Status {
	if x != nil {
		return x.Err
	}
	return nil
}

type DeviceUnBindRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceInfo *DeviceInfo `protobuf:"bytes,1,opt,name=deviceInfo,proto3" json:"deviceInfo,omitempty"`
}

func (x *DeviceUnBindRequest) Reset() {
	*x = DeviceUnBindRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_router_v1_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceUnBindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceUnBindRequest) ProtoMessage() {}

func (x *DeviceUnBindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_router_v1_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceUnBindRequest.ProtoReflect.Descriptor instead.
func (*DeviceUnBindRequest) Descriptor() ([]byte, []int) {
	return file_api_router_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *DeviceUnBindRequest) GetDeviceInfo() *DeviceInfo {
	if x != nil {
		return x.DeviceInfo
	}
	return nil
}

type DeviceUnBindReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret bool           `protobuf:"varint,1,opt,name=ret,proto3" json:"ret,omitempty"`
	Err *errors.Status `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"` //kratos通用错误
}

func (x *DeviceUnBindReply) Reset() {
	*x = DeviceUnBindReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_router_v1_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceUnBindReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceUnBindReply) ProtoMessage() {}

func (x *DeviceUnBindReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_router_v1_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceUnBindReply.ProtoReflect.Descriptor instead.
func (*DeviceUnBindReply) Descriptor() ([]byte, []int) {
	return file_api_router_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *DeviceUnBindReply) GetRet() bool {
	if x != nil {
		return x.Ret
	}
	return false
}

func (x *DeviceUnBindReply) GetErr() *errors.Status {
	if x != nil {
		return x.Err
	}
	return nil
}

type RoutersByUserIdsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserIds []uint64 `protobuf:"varint,1,rep,packed,name=userIds,proto3" json:"userIds,omitempty"`
}

func (x *RoutersByUserIdsRequest) Reset() {
	*x = RoutersByUserIdsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_router_v1_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoutersByUserIdsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutersByUserIdsRequest) ProtoMessage() {}

func (x *RoutersByUserIdsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_router_v1_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutersByUserIdsRequest.ProtoReflect.Descriptor instead.
func (*RoutersByUserIdsRequest) Descriptor() ([]byte, []int) {
	return file_api_router_v1_service_proto_rawDescGZIP(), []int{5}
}

func (x *RoutersByUserIdsRequest) GetUserIds() []uint64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type RoutersByUserIdsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret               bool                                                `protobuf:"varint,1,opt,name=ret,proto3" json:"ret,omitempty"`
	UserDevicesRouter map[string]*RoutersByUserIdsReply_UserDevicesRouter `protobuf:"bytes,2,rep,name=userDevicesRouter,proto3" json:"userDevicesRouter,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Err               *errors.Status                                      `protobuf:"bytes,3,opt,name=err,proto3" json:"err,omitempty"` //kratos通用错误
}

func (x *RoutersByUserIdsReply) Reset() {
	*x = RoutersByUserIdsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_router_v1_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoutersByUserIdsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutersByUserIdsReply) ProtoMessage() {}

func (x *RoutersByUserIdsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_router_v1_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutersByUserIdsReply.ProtoReflect.Descriptor instead.
func (*RoutersByUserIdsReply) Descriptor() ([]byte, []int) {
	return file_api_router_v1_service_proto_rawDescGZIP(), []int{6}
}

func (x *RoutersByUserIdsReply) GetRet() bool {
	if x != nil {
		return x.Ret
	}
	return false
}

func (x *RoutersByUserIdsReply) GetUserDevicesRouter() map[string]*RoutersByUserIdsReply_UserDevicesRouter {
	if x != nil {
		return x.UserDevicesRouter
	}
	return nil
}

func (x *RoutersByUserIdsReply) GetErr() *errors.Status {
	if x != nil {
		return x.Err
	}
	return nil
}

type SaveRoomServerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
}

func (x *SaveRoomServerRequest) Reset() {
	*x = SaveRoomServerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_router_v1_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveRoomServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveRoomServerRequest) ProtoMessage() {}

func (x *SaveRoomServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_router_v1_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveRoomServerRequest.ProtoReflect.Descriptor instead.
func (*SaveRoomServerRequest) Descriptor() ([]byte, []int) {
	return file_api_router_v1_service_proto_rawDescGZIP(), []int{7}
}

func (x *SaveRoomServerRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type SaveRoomServerReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids map[string]string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Err *errors.Status    `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"` //kratos通用错误
}

func (x *SaveRoomServerReply) Reset() {
	*x = SaveRoomServerReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_router_v1_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveRoomServerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveRoomServerReply) ProtoMessage() {}

func (x *SaveRoomServerReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_router_v1_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveRoomServerReply.ProtoReflect.Descriptor instead.
func (*SaveRoomServerReply) Descriptor() ([]byte, []int) {
	return file_api_router_v1_service_proto_rawDescGZIP(), []int{8}
}

func (x *SaveRoomServerReply) GetIds() map[string]string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *SaveRoomServerReply) GetErr() *errors.Status {
	if x != nil {
		return x.Err
	}
	return nil
}

type SaveLocalRoomServerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id []string `protobuf:"bytes,1,rep,name=id,proto3" json:"id,omitempty"`
}

func (x *SaveLocalRoomServerRequest) Reset() {
	*x = SaveLocalRoomServerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_router_v1_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveLocalRoomServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveLocalRoomServerRequest) ProtoMessage() {}

func (x *SaveLocalRoomServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_router_v1_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveLocalRoomServerRequest.ProtoReflect.Descriptor instead.
func (*SaveLocalRoomServerRequest) Descriptor() ([]byte, []int) {
	return file_api_router_v1_service_proto_rawDescGZIP(), []int{9}
}

func (x *SaveLocalRoomServerRequest) GetId() []string {
	if x != nil {
		return x.Id
	}
	return nil
}

type SaveLocalRoomServerReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids map[string]string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Err *errors.Status    `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"` //kratos通用错误
}

func (x *SaveLocalRoomServerReply) Reset() {
	*x = SaveLocalRoomServerReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_router_v1_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveLocalRoomServerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveLocalRoomServerReply) ProtoMessage() {}

func (x *SaveLocalRoomServerReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_router_v1_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveLocalRoomServerReply.ProtoReflect.Descriptor instead.
func (*SaveLocalRoomServerReply) Descriptor() ([]byte, []int) {
	return file_api_router_v1_service_proto_rawDescGZIP(), []int{10}
}

func (x *SaveLocalRoomServerReply) GetIds() map[string]string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *SaveLocalRoomServerReply) GetErr() *errors.Status {
	if x != nil {
		return x.Err
	}
	return nil
}

type GetRoomServerByIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id []string `protobuf:"bytes,1,rep,name=id,proto3" json:"id,omitempty"`
}

func (x *GetRoomServerByIDRequest) Reset() {
	*x = GetRoomServerByIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_router_v1_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRoomServerByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomServerByIDRequest) ProtoMessage() {}

func (x *GetRoomServerByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_router_v1_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomServerByIDRequest.ProtoReflect.Descriptor instead.
func (*GetRoomServerByIDRequest) Descriptor() ([]byte, []int) {
	return file_api_router_v1_service_proto_rawDescGZIP(), []int{11}
}

func (x *GetRoomServerByIDRequest) GetId() []string {
	if x != nil {
		return x.Id
	}
	return nil
}

type GetRoomServerByIDReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids map[string]string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Err *errors.Status    `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"` //kratos通用错误
}

func (x *GetRoomServerByIDReply) Reset() {
	*x = GetRoomServerByIDReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_router_v1_service_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRoomServerByIDReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomServerByIDReply) ProtoMessage() {}

func (x *GetRoomServerByIDReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_router_v1_service_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomServerByIDReply.ProtoReflect.Descriptor instead.
func (*GetRoomServerByIDReply) Descriptor() ([]byte, []int) {
	return file_api_router_v1_service_proto_rawDescGZIP(), []int{12}
}

func (x *GetRoomServerByIDReply) GetIds() map[string]string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *GetRoomServerByIDReply) GetErr() *errors.Status {
	if x != nil {
		return x.Err
	}
	return nil
}

type GetLocalRoomServerByIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id []string `protobuf:"bytes,1,rep,name=id,proto3" json:"id,omitempty"`
}

func (x *GetLocalRoomServerByIDRequest) Reset() {
	*x = GetLocalRoomServerByIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_router_v1_service_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLocalRoomServerByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLocalRoomServerByIDRequest) ProtoMessage() {}

func (x *GetLocalRoomServerByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_router_v1_service_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLocalRoomServerByIDRequest.ProtoReflect.Descriptor instead.
func (*GetLocalRoomServerByIDRequest) Descriptor() ([]byte, []int) {
	return file_api_router_v1_service_proto_rawDescGZIP(), []int{13}
}

func (x *GetLocalRoomServerByIDRequest) GetId() []string {
	if x != nil {
		return x.Id
	}
	return nil
}

type GetLocalRoomServerByIDReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids map[string]string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Err *errors.Status    `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"` //kratos通用错误
}

func (x *GetLocalRoomServerByIDReply) Reset() {
	*x = GetLocalRoomServerByIDReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_router_v1_service_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLocalRoomServerByIDReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLocalRoomServerByIDReply) ProtoMessage() {}

func (x *GetLocalRoomServerByIDReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_router_v1_service_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLocalRoomServerByIDReply.ProtoReflect.Descriptor instead.
func (*GetLocalRoomServerByIDReply) Descriptor() ([]byte, []int) {
	return file_api_router_v1_service_proto_rawDescGZIP(), []int{14}
}

func (x *GetLocalRoomServerByIDReply) GetIds() map[string]string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *GetLocalRoomServerByIDReply) GetErr() *errors.Status {
	if x != nil {
		return x.Err
	}
	return nil
}

type SaveRoomRouterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId    uint64   `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	GwServers []string `protobuf:"bytes,2,rep,name=gwServers,proto3" json:"gwServers,omitempty"`
}

func (x *SaveRoomRouterRequest) Reset() {
	*x = SaveRoomRouterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_router_v1_service_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveRoomRouterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveRoomRouterRequest) ProtoMessage() {}

func (x *SaveRoomRouterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_router_v1_service_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveRoomRouterRequest.ProtoReflect.Descriptor instead.
func (*SaveRoomRouterRequest) Descriptor() ([]byte, []int) {
	return file_api_router_v1_service_proto_rawDescGZIP(), []int{15}
}

func (x *SaveRoomRouterRequest) GetRoomId() uint64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *SaveRoomRouterRequest) GetGwServers() []string {
	if x != nil {
		return x.GwServers
	}
	return nil
}

type SaveRoomRouterReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret bool           `protobuf:"varint,1,opt,name=ret,proto3" json:"ret,omitempty"`
	Err *errors.Status `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"` //kratos通用错误
}

func (x *SaveRoomRouterReply) Reset() {
	*x = SaveRoomRouterReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_router_v1_service_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveRoomRouterReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveRoomRouterReply) ProtoMessage() {}

func (x *SaveRoomRouterReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_router_v1_service_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveRoomRouterReply.ProtoReflect.Descriptor instead.
func (*SaveRoomRouterReply) Descriptor() ([]byte, []int) {
	return file_api_router_v1_service_proto_rawDescGZIP(), []int{16}
}

func (x *SaveRoomRouterReply) GetRet() bool {
	if x != nil {
		return x.Ret
	}
	return false
}

func (x *SaveRoomRouterReply) GetErr() *errors.Status {
	if x != nil {
		return x.Err
	}
	return nil
}

type DeleteRoomServerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId    uint64   `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	GwServers []string `protobuf:"bytes,2,rep,name=gwServers,proto3" json:"gwServers,omitempty"` //删除的网关地址列表
}

func (x *DeleteRoomServerRequest) Reset() {
	*x = DeleteRoomServerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_router_v1_service_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRoomServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoomServerRequest) ProtoMessage() {}

func (x *DeleteRoomServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_router_v1_service_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoomServerRequest.ProtoReflect.Descriptor instead.
func (*DeleteRoomServerRequest) Descriptor() ([]byte, []int) {
	return file_api_router_v1_service_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteRoomServerRequest) GetRoomId() uint64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *DeleteRoomServerRequest) GetGwServers() []string {
	if x != nil {
		return x.GwServers
	}
	return nil
}

type DeleteRoomServerReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret bool           `protobuf:"varint,1,opt,name=ret,proto3" json:"ret,omitempty"`
	Err *errors.Status `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"` //kratos通用错误
}

func (x *DeleteRoomServerReply) Reset() {
	*x = DeleteRoomServerReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_router_v1_service_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRoomServerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoomServerReply) ProtoMessage() {}

func (x *DeleteRoomServerReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_router_v1_service_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoomServerReply.ProtoReflect.Descriptor instead.
func (*DeleteRoomServerReply) Descriptor() ([]byte, []int) {
	return file_api_router_v1_service_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteRoomServerReply) GetRet() bool {
	if x != nil {
		return x.Ret
	}
	return false
}

func (x *DeleteRoomServerReply) GetErr() *errors.Status {
	if x != nil {
		return x.Err
	}
	return nil
}

type GetRoomRouterByIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId    uint64   `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	GwServers []string `protobuf:"bytes,2,rep,name=gwServers,proto3" json:"gwServers,omitempty"`
}

func (x *GetRoomRouterByIDRequest) Reset() {
	*x = GetRoomRouterByIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_router_v1_service_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRoomRouterByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomRouterByIDRequest) ProtoMessage() {}

func (x *GetRoomRouterByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_router_v1_service_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomRouterByIDRequest.ProtoReflect.Descriptor instead.
func (*GetRoomRouterByIDRequest) Descriptor() ([]byte, []int) {
	return file_api_router_v1_service_proto_rawDescGZIP(), []int{19}
}

func (x *GetRoomRouterByIDRequest) GetRoomId() uint64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *GetRoomRouterByIDRequest) GetGwServers() []string {
	if x != nil {
		return x.GwServers
	}
	return nil
}

type GetRoomRouterByIDReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret       bool           `protobuf:"varint,1,opt,name=ret,proto3" json:"ret,omitempty"`
	GwServers []string       `protobuf:"bytes,2,rep,name=gwServers,proto3" json:"gwServers,omitempty"`
	Err       *errors.Status `protobuf:"bytes,3,opt,name=err,proto3" json:"err,omitempty"` //kratos通用错误
}

func (x *GetRoomRouterByIDReply) Reset() {
	*x = GetRoomRouterByIDReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_router_v1_service_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRoomRouterByIDReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomRouterByIDReply) ProtoMessage() {}

func (x *GetRoomRouterByIDReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_router_v1_service_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomRouterByIDReply.ProtoReflect.Descriptor instead.
func (*GetRoomRouterByIDReply) Descriptor() ([]byte, []int) {
	return file_api_router_v1_service_proto_rawDescGZIP(), []int{20}
}

func (x *GetRoomRouterByIDReply) GetRet() bool {
	if x != nil {
		return x.Ret
	}
	return false
}

func (x *GetRoomRouterByIDReply) GetGwServers() []string {
	if x != nil {
		return x.GwServers
	}
	return nil
}

func (x *GetRoomRouterByIDReply) GetErr() *errors.Status {
	if x != nil {
		return x.Err
	}
	return nil
}

type RoutersByUserIdsReply_UserDevicesRouter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceInfo []*DeviceInfo `protobuf:"bytes,1,rep,name=deviceInfo,proto3" json:"deviceInfo,omitempty"`
}

func (x *RoutersByUserIdsReply_UserDevicesRouter) Reset() {
	*x = RoutersByUserIdsReply_UserDevicesRouter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_router_v1_service_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoutersByUserIdsReply_UserDevicesRouter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutersByUserIdsReply_UserDevicesRouter) ProtoMessage() {}

func (x *RoutersByUserIdsReply_UserDevicesRouter) ProtoReflect() protoreflect.Message {
	mi := &file_api_router_v1_service_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutersByUserIdsReply_UserDevicesRouter.ProtoReflect.Descriptor instead.
func (*RoutersByUserIdsReply_UserDevicesRouter) Descriptor() ([]byte, []int) {
	return file_api_router_v1_service_proto_rawDescGZIP(), []int{6, 0}
}

func (x *RoutersByUserIdsReply_UserDevicesRouter) GetDeviceInfo() []*DeviceInfo {
	if x != nil {
		return x.DeviceInfo
	}
	return nil
}

var File_api_router_v1_service_proto protoreflect.FileDescriptor

var file_api_router_v1_service_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x61, 0x70, 0x69, 0x2f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x2f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x73,
	0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x1a, 0x13, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x73, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x1c, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x76, 0x31,
	0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc5, 0x01,
	0x0a, 0x0a, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1a, 0x0a, 0x08,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x49, 0x44, 0x12, 0x26, 0x0a, 0x0e, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x53,
	0x65, 0x71, 0x75, 0x65, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0e, 0x63, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x53, 0x65, 0x71, 0x75, 0x65, 0x63, 0x65, 0x12, 0x1e, 0x0a, 0x0a,
	0x63, 0x75, 0x72, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0a, 0x63, 0x75, 0x72, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x37, 0x0a, 0x0a,
	0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x44,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x64, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x22, 0x4c, 0x0a, 0x11, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x42,
	0x69, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x37, 0x0a, 0x0a, 0x64, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17,
	0x2e, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x22, 0x74, 0x0a, 0x0f, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x42, 0x69, 0x6e,
	0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x03, 0x72, 0x65, 0x74, 0x12, 0x2d, 0x0a, 0x05, 0x65, 0x78, 0x69, 0x73,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e,
	0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x05, 0x65, 0x78, 0x69, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2e, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x03, 0x65, 0x72, 0x72, 0x22, 0x4e, 0x0a, 0x13, 0x44, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x55, 0x6e, 0x42, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x37, 0x0a, 0x0a, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a, 0x64,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x47, 0x0a, 0x11, 0x44, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x55, 0x6e, 0x42, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x72, 0x65, 0x74,
	0x12, 0x20, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x03, 0x65,
	0x72, 0x72, 0x22, 0x33, 0x0a, 0x17, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x73, 0x42, 0x79, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x04, 0x52, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x73, 0x22, 0xfe, 0x02, 0x0a, 0x15, 0x52, 0x6f, 0x75, 0x74,
	0x65, 0x72, 0x73, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x73, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03,
	0x72, 0x65, 0x74, 0x12, 0x67, 0x0a, 0x11, 0x75, 0x73, 0x65, 0x72, 0x44, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x39,
	0x2e, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x6f, 0x75,
	0x74, 0x65, 0x72, 0x73, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x73, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x52, 0x6f,
	0x75, 0x74, 0x65, 0x72, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x11, 0x75, 0x73, 0x65, 0x72, 0x44,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x12, 0x20, 0x0a, 0x03,
	0x65, 0x72, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x73, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x03, 0x65, 0x72, 0x72, 0x1a, 0x4c,
	0x0a, 0x11, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x52, 0x6f, 0x75,
	0x74, 0x65, 0x72, 0x12, 0x37, 0x0a, 0x0a, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e,
	0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x0a, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x7a, 0x0a, 0x16,
	0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x52, 0x6f, 0x75, 0x74, 0x65,
	0x72, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x4a, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x34, 0x2e, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e,
	0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x73, 0x42, 0x79, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x29, 0x0a, 0x15, 0x53, 0x61, 0x76, 0x65,
	0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03,
	0x69, 0x64, 0x73, 0x22, 0xac, 0x01, 0x0a, 0x13, 0x53, 0x61, 0x76, 0x65, 0x52, 0x6f, 0x6f, 0x6d,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x3b, 0x0a, 0x03, 0x69,
	0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x73, 0x65, 0x71, 0x75, 0x65,
	0x6e, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x49, 0x64, 0x73, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x03, 0x69, 0x64, 0x73, 0x12, 0x20, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2e, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x03, 0x65, 0x72, 0x72, 0x1a, 0x36, 0x0a, 0x08, 0x49, 0x64,
	0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02,
	0x38, 0x01, 0x22, 0x2c, 0x0a, 0x1a, 0x53, 0x61, 0x76, 0x65, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x52,
	0x6f, 0x6f, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x22, 0xb6, 0x01, 0x0a, 0x18, 0x53, 0x61, 0x76, 0x65, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x52, 0x6f,
	0x6f, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x40, 0x0a,
	0x03, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x73, 0x65, 0x71,
	0x75, 0x65, 0x6e, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x4c, 0x6f, 0x63,
	0x61, 0x6c, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x2e, 0x49, 0x64, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x03, 0x69, 0x64, 0x73, 0x12,
	0x20, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x73, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x03, 0x65, 0x72,
	0x72, 0x1a, 0x36, 0x0a, 0x08, 0x49, 0x64, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x2a, 0x0a, 0x18, 0x47, 0x65, 0x74,
	0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0xb2, 0x01, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6f,
	0x6d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x3e, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2c, 0x2e,
	0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x52,
	0x6f, 0x6f, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x2e, 0x49, 0x64, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x03, 0x69, 0x64, 0x73,
	0x12, 0x20, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x03, 0x65,
	0x72, 0x72, 0x1a, 0x36, 0x0a, 0x08, 0x49, 0x64, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x2f, 0x0a, 0x1d, 0x47, 0x65,
	0x74, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0xbc, 0x01, 0x0a, 0x1b,
	0x47, 0x65, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x43, 0x0a, 0x03, 0x69,
	0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x31, 0x2e, 0x73, 0x65, 0x71, 0x75, 0x65,
	0x6e, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x52,
	0x6f, 0x6f, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x2e, 0x49, 0x64, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x03, 0x69, 0x64, 0x73,
	0x12, 0x20, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x03, 0x65,
	0x72, 0x72, 0x1a, 0x36, 0x0a, 0x08, 0x49, 0x64, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x4d, 0x0a, 0x15, 0x53, 0x61,
	0x76, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x67,
	0x77, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09,
	0x67, 0x77, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x22, 0x49, 0x0a, 0x13, 0x53, 0x61, 0x76,
	0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x72,
	0x65, 0x74, 0x12, 0x20, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x03, 0x65, 0x72, 0x72, 0x22, 0x4f, 0x0a, 0x17, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x6f,
	0x6f, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x67, 0x77, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x67, 0x77, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x73, 0x22, 0x4b, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52,
	0x6f, 0x6f, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x72, 0x65, 0x74,
	0x12, 0x20, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x03, 0x65,
	0x72, 0x72, 0x22, 0x50, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x6f, 0x75,
	0x74, 0x65, 0x72, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06,
	0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x67, 0x77, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x67, 0x77, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x73, 0x22, 0x6a, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x52,
	0x6f, 0x75, 0x74, 0x65, 0x72, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x72, 0x65, 0x74,
	0x12, 0x1c, 0x0a, 0x09, 0x67, 0x77, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x09, 0x67, 0x77, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x12, 0x20,
	0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x73, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x03, 0x65, 0x72, 0x72,
	0x32, 0x98, 0x05, 0x0a, 0x06, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x12, 0x50, 0x0a, 0x0e, 0x55,
	0x73, 0x65, 0x72, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x42, 0x69, 0x6e, 0x64, 0x12, 0x1e, 0x2e,
	0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x42, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e,
	0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x42, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x56, 0x0a,
	0x10, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x55, 0x6e, 0x42, 0x69, 0x6e,
	0x64, 0x12, 0x20, 0x2e, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x55, 0x6e, 0x42, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x55, 0x6e, 0x42, 0x69, 0x6e, 0x64, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x61, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x75, 0x74,
	0x65, 0x72, 0x73, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x73, 0x12, 0x24, 0x2e, 0x73,
	0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x6f, 0x75, 0x74, 0x65,
	0x72, 0x73, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x22, 0x2e, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x73, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x66, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x4c,
	0x6f, 0x63, 0x61, 0x6c, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x73, 0x42, 0x79, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x73, 0x12, 0x24, 0x2e, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x73, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x73, 0x65, 0x71,
	0x75, 0x65, 0x6e, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x73,
	0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00,
	0x12, 0x58, 0x0a, 0x0e, 0x53, 0x61, 0x76, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x6f, 0x75, 0x74,
	0x65, 0x72, 0x12, 0x22, 0x2e, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x53, 0x61, 0x76, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x6f, 0x75,
	0x74, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x5c, 0x0a, 0x10, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x12, 0x24,
	0x2e, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x61, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x52,
	0x6f, 0x6f, 0x6d, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x42, 0x79, 0x49, 0x44, 0x12, 0x25, 0x2e,
	0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x52,
	0x6f, 0x6f, 0x6d, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x72,
	0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x32, 0x0a, 0x09, 0x72,
	0x6f, 0x75, 0x74, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a, 0x18, 0x78, 0x68, 0x61, 0x70,
	0x70, 0x65, 0x6e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2f, 0x76,
	0x31, 0x3b, 0x76, 0x31, 0xa2, 0x02, 0x08, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x56, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_router_v1_service_proto_rawDescOnce sync.Once
	file_api_router_v1_service_proto_rawDescData = file_api_router_v1_service_proto_rawDesc
)

func file_api_router_v1_service_proto_rawDescGZIP() []byte {
	file_api_router_v1_service_proto_rawDescOnce.Do(func() {
		file_api_router_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_router_v1_service_proto_rawDescData)
	})
	return file_api_router_v1_service_proto_rawDescData
}

var file_api_router_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_api_router_v1_service_proto_goTypes = []interface{}{
	(*DeviceInfo)(nil),                              // 0: sequence.v1.DeviceInfo
	(*DeviceBindRequest)(nil),                       // 1: sequence.v1.DeviceBindRequest
	(*DeviceBindReply)(nil),                         // 2: sequence.v1.DeviceBindReply
	(*DeviceUnBindRequest)(nil),                     // 3: sequence.v1.DeviceUnBindRequest
	(*DeviceUnBindReply)(nil),                       // 4: sequence.v1.DeviceUnBindReply
	(*RoutersByUserIdsRequest)(nil),                 // 5: sequence.v1.RoutersByUserIdsRequest
	(*RoutersByUserIdsReply)(nil),                   // 6: sequence.v1.RoutersByUserIdsReply
	(*SaveRoomServerRequest)(nil),                   // 7: sequence.v1.SaveRoomServerRequest
	(*SaveRoomServerReply)(nil),                     // 8: sequence.v1.SaveRoomServerReply
	(*SaveLocalRoomServerRequest)(nil),              // 9: sequence.v1.SaveLocalRoomServerRequest
	(*SaveLocalRoomServerReply)(nil),                // 10: sequence.v1.SaveLocalRoomServerReply
	(*GetRoomServerByIDRequest)(nil),                // 11: sequence.v1.GetRoomServerByIDRequest
	(*GetRoomServerByIDReply)(nil),                  // 12: sequence.v1.GetRoomServerByIDReply
	(*GetLocalRoomServerByIDRequest)(nil),           // 13: sequence.v1.GetLocalRoomServerByIDRequest
	(*GetLocalRoomServerByIDReply)(nil),             // 14: sequence.v1.GetLocalRoomServerByIDReply
	(*SaveRoomRouterRequest)(nil),                   // 15: sequence.v1.SaveRoomRouterRequest
	(*SaveRoomRouterReply)(nil),                     // 16: sequence.v1.SaveRoomRouterReply
	(*DeleteRoomServerRequest)(nil),                 // 17: sequence.v1.DeleteRoomServerRequest
	(*DeleteRoomServerReply)(nil),                   // 18: sequence.v1.DeleteRoomServerReply
	(*GetRoomRouterByIDRequest)(nil),                // 19: sequence.v1.GetRoomRouterByIDRequest
	(*GetRoomRouterByIDReply)(nil),                  // 20: sequence.v1.GetRoomRouterByIDReply
	(*RoutersByUserIdsReply_UserDevicesRouter)(nil), // 21: sequence.v1.RoutersByUserIdsReply.UserDevicesRouter
	nil,                   // 22: sequence.v1.RoutersByUserIdsReply.UserDevicesRouterEntry
	nil,                   // 23: sequence.v1.SaveRoomServerReply.IdsEntry
	nil,                   // 24: sequence.v1.SaveLocalRoomServerReply.IdsEntry
	nil,                   // 25: sequence.v1.GetRoomServerByIDReply.IdsEntry
	nil,                   // 26: sequence.v1.GetLocalRoomServerByIDReply.IdsEntry
	(v1.DeviceType)(0),    // 27: protocol.v1.DeviceType
	(*errors.Status)(nil), // 28: errors.Status
}
var file_api_router_v1_service_proto_depIdxs = []int32{
	27, // 0: sequence.v1.DeviceInfo.deviceType:type_name -> protocol.v1.DeviceType
	0,  // 1: sequence.v1.DeviceBindRequest.deviceInfo:type_name -> sequence.v1.DeviceInfo
	0,  // 2: sequence.v1.DeviceBindReply.exist:type_name -> sequence.v1.DeviceInfo
	28, // 3: sequence.v1.DeviceBindReply.err:type_name -> errors.Status
	0,  // 4: sequence.v1.DeviceUnBindRequest.deviceInfo:type_name -> sequence.v1.DeviceInfo
	28, // 5: sequence.v1.DeviceUnBindReply.err:type_name -> errors.Status
	22, // 6: sequence.v1.RoutersByUserIdsReply.userDevicesRouter:type_name -> sequence.v1.RoutersByUserIdsReply.UserDevicesRouterEntry
	28, // 7: sequence.v1.RoutersByUserIdsReply.err:type_name -> errors.Status
	23, // 8: sequence.v1.SaveRoomServerReply.ids:type_name -> sequence.v1.SaveRoomServerReply.IdsEntry
	28, // 9: sequence.v1.SaveRoomServerReply.err:type_name -> errors.Status
	24, // 10: sequence.v1.SaveLocalRoomServerReply.ids:type_name -> sequence.v1.SaveLocalRoomServerReply.IdsEntry
	28, // 11: sequence.v1.SaveLocalRoomServerReply.err:type_name -> errors.Status
	25, // 12: sequence.v1.GetRoomServerByIDReply.ids:type_name -> sequence.v1.GetRoomServerByIDReply.IdsEntry
	28, // 13: sequence.v1.GetRoomServerByIDReply.err:type_name -> errors.Status
	26, // 14: sequence.v1.GetLocalRoomServerByIDReply.ids:type_name -> sequence.v1.GetLocalRoomServerByIDReply.IdsEntry
	28, // 15: sequence.v1.GetLocalRoomServerByIDReply.err:type_name -> errors.Status
	28, // 16: sequence.v1.SaveRoomRouterReply.err:type_name -> errors.Status
	28, // 17: sequence.v1.DeleteRoomServerReply.err:type_name -> errors.Status
	28, // 18: sequence.v1.GetRoomRouterByIDReply.err:type_name -> errors.Status
	0,  // 19: sequence.v1.RoutersByUserIdsReply.UserDevicesRouter.deviceInfo:type_name -> sequence.v1.DeviceInfo
	21, // 20: sequence.v1.RoutersByUserIdsReply.UserDevicesRouterEntry.value:type_name -> sequence.v1.RoutersByUserIdsReply.UserDevicesRouter
	1,  // 21: sequence.v1.Router.UserDeviceBind:input_type -> sequence.v1.DeviceBindRequest
	3,  // 22: sequence.v1.Router.UserDeviceUnBind:input_type -> sequence.v1.DeviceUnBindRequest
	5,  // 23: sequence.v1.Router.GetRoutersByUserIds:input_type -> sequence.v1.RoutersByUserIdsRequest
	5,  // 24: sequence.v1.Router.GetLocalRoutersByUserIds:input_type -> sequence.v1.RoutersByUserIdsRequest
	15, // 25: sequence.v1.Router.SaveRoomRouter:input_type -> sequence.v1.SaveRoomRouterRequest
	17, // 26: sequence.v1.Router.DeleteRoomRouter:input_type -> sequence.v1.DeleteRoomServerRequest
	19, // 27: sequence.v1.Router.GetRoomRouterByID:input_type -> sequence.v1.GetRoomRouterByIDRequest
	2,  // 28: sequence.v1.Router.UserDeviceBind:output_type -> sequence.v1.DeviceBindReply
	4,  // 29: sequence.v1.Router.UserDeviceUnBind:output_type -> sequence.v1.DeviceUnBindReply
	6,  // 30: sequence.v1.Router.GetRoutersByUserIds:output_type -> sequence.v1.RoutersByUserIdsReply
	6,  // 31: sequence.v1.Router.GetLocalRoutersByUserIds:output_type -> sequence.v1.RoutersByUserIdsReply
	16, // 32: sequence.v1.Router.SaveRoomRouter:output_type -> sequence.v1.SaveRoomRouterReply
	8,  // 33: sequence.v1.Router.DeleteRoomRouter:output_type -> sequence.v1.SaveRoomServerReply
	20, // 34: sequence.v1.Router.GetRoomRouterByID:output_type -> sequence.v1.GetRoomRouterByIDReply
	28, // [28:35] is the sub-list for method output_type
	21, // [21:28] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_api_router_v1_service_proto_init() }
func file_api_router_v1_service_proto_init() {
	if File_api_router_v1_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_router_v1_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_router_v1_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceBindRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_router_v1_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceBindReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_router_v1_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceUnBindRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_router_v1_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceUnBindReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_router_v1_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoutersByUserIdsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_router_v1_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoutersByUserIdsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_router_v1_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveRoomServerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_router_v1_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveRoomServerReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_router_v1_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveLocalRoomServerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_router_v1_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveLocalRoomServerReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_router_v1_service_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRoomServerByIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_router_v1_service_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRoomServerByIDReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_router_v1_service_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLocalRoomServerByIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_router_v1_service_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLocalRoomServerByIDReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_router_v1_service_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveRoomRouterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_router_v1_service_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveRoomRouterReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_router_v1_service_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteRoomServerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_router_v1_service_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteRoomServerReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_router_v1_service_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRoomRouterByIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_router_v1_service_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRoomRouterByIDReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_router_v1_service_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoutersByUserIdsReply_UserDevicesRouter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_router_v1_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_router_v1_service_proto_goTypes,
		DependencyIndexes: file_api_router_v1_service_proto_depIdxs,
		MessageInfos:      file_api_router_v1_service_proto_msgTypes,
	}.Build()
	File_api_router_v1_service_proto = out.File
	file_api_router_v1_service_proto_rawDesc = nil
	file_api_router_v1_service_proto_goTypes = nil
	file_api_router_v1_service_proto_depIdxs = nil
}
