// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.15.6
// source: api/router/v1/service.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Router_GetServerByID_FullMethodName      = "/sequence.v1.Router/GetServerByID"
	Router_GetLocalServerByID_FullMethodName = "/sequence.v1.Router/GetLocalServerByID"
)

// RouterClient is the client API for Router service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RouterClient interface {
	GetServerByID(ctx context.Context, in *GetServerByIDRequest, opts ...grpc.CallOption) (*GetServerByIDReply, error)
	GetLocalServerByID(ctx context.Context, in *GetServerByIDRequest, opts ...grpc.CallOption) (*GetServerByIDReply, error)
}

type routerClient struct {
	cc grpc.ClientConnInterface
}

func NewRouterClient(cc grpc.ClientConnInterface) RouterClient {
	return &routerClient{cc}
}

func (c *routerClient) GetServerByID(ctx context.Context, in *GetServerByIDRequest, opts ...grpc.CallOption) (*GetServerByIDReply, error) {
	out := new(GetServerByIDReply)
	err := c.cc.Invoke(ctx, Router_GetServerByID_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerClient) GetLocalServerByID(ctx context.Context, in *GetServerByIDRequest, opts ...grpc.CallOption) (*GetServerByIDReply, error) {
	out := new(GetServerByIDReply)
	err := c.cc.Invoke(ctx, Router_GetLocalServerByID_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RouterServer is the server API for Router service.
// All implementations must embed UnimplementedRouterServer
// for forward compatibility
type RouterServer interface {
	GetServerByID(context.Context, *GetServerByIDRequest) (*GetServerByIDReply, error)
	GetLocalServerByID(context.Context, *GetServerByIDRequest) (*GetServerByIDReply, error)
	mustEmbedUnimplementedRouterServer()
}

// UnimplementedRouterServer must be embedded to have forward compatible implementations.
type UnimplementedRouterServer struct {
}

func (UnimplementedRouterServer) GetServerByID(context.Context, *GetServerByIDRequest) (*GetServerByIDReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetServerByID not implemented")
}
func (UnimplementedRouterServer) GetLocalServerByID(context.Context, *GetServerByIDRequest) (*GetServerByIDReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLocalServerByID not implemented")
}
func (UnimplementedRouterServer) mustEmbedUnimplementedRouterServer() {}

// UnsafeRouterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RouterServer will
// result in compilation errors.
type UnsafeRouterServer interface {
	mustEmbedUnimplementedRouterServer()
}

func RegisterRouterServer(s grpc.ServiceRegistrar, srv RouterServer) {
	s.RegisterService(&Router_ServiceDesc, srv)
}

func _Router_GetServerByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServerByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).GetServerByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Router_GetServerByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).GetServerByID(ctx, req.(*GetServerByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Router_GetLocalServerByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServerByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).GetLocalServerByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Router_GetLocalServerByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).GetLocalServerByID(ctx, req.(*GetServerByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Router_ServiceDesc is the grpc.ServiceDesc for Router service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Router_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sequence.v1.Router",
	HandlerType: (*RouterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetServerByID",
			Handler:    _Router_GetServerByID_Handler,
		},
		{
			MethodName: "GetLocalServerByID",
			Handler:    _Router_GetLocalServerByID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/router/v1/service.proto",
}
