// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: api/protocol/v1/common.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeviceType int32

const (
	DeviceType_IOS        DeviceType = 0 //iOS
	DeviceType_ANDROID    DeviceType = 1 //安卓
	DeviceType_WEB        DeviceType = 2 //web端
	DeviceType_MINIWECHAT DeviceType = 3 //微信小程序
	DeviceType_UNKNOW     DeviceType = 9 //未知类型
)

// Enum value maps for DeviceType.
var (
	DeviceType_name = map[int32]string{
		0: "IOS",
		1: "ANDROID",
		2: "WEB",
		3: "MINIWECHAT",
		9: "UNKNOW",
	}
	DeviceType_value = map[string]int32{
		"IOS":        0,
		"ANDROID":    1,
		"WEB":        2,
		"MINIWECHAT": 3,
		"UNKNOW":     9,
	}
)

func (x DeviceType) Enum() *DeviceType {
	p := new(DeviceType)
	*p = x
	return p
}

func (x DeviceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_protocol_v1_common_proto_enumTypes[0].Descriptor()
}

func (DeviceType) Type() protoreflect.EnumType {
	return &file_api_protocol_v1_common_proto_enumTypes[0]
}

func (x DeviceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceType.Descriptor instead.
func (DeviceType) EnumDescriptor() ([]byte, []int) {
	return file_api_protocol_v1_common_proto_rawDescGZIP(), []int{0}
}

type LoginType int32

const (
	LoginType_MANUAL LoginType = 0 //手工登录
	LoginType_AUTO   LoginType = 1 //自动登录
)

// Enum value maps for LoginType.
var (
	LoginType_name = map[int32]string{
		0: "MANUAL",
		1: "AUTO",
	}
	LoginType_value = map[string]int32{
		"MANUAL": 0,
		"AUTO":   1,
	}
)

func (x LoginType) Enum() *LoginType {
	p := new(LoginType)
	*p = x
	return p
}

func (x LoginType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LoginType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_protocol_v1_common_proto_enumTypes[1].Descriptor()
}

func (LoginType) Type() protoreflect.EnumType {
	return &file_api_protocol_v1_common_proto_enumTypes[1]
}

func (x LoginType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LoginType.Descriptor instead.
func (LoginType) EnumDescriptor() ([]byte, []int) {
	return file_api_protocol_v1_common_proto_rawDescGZIP(), []int{1}
}

type RoleType int32

const (
	RoleType_ROLE_NORMAL           RoleType = 0 //默认类型为普通用户
	RoleType_ROLE_ADMIN            RoleType = 1 //管理员用户
	RoleType_ROLE_CUSTOMER_SERVICE RoleType = 2 //客服用户
)

// Enum value maps for RoleType.
var (
	RoleType_name = map[int32]string{
		0: "ROLE_NORMAL",
		1: "ROLE_ADMIN",
		2: "ROLE_CUSTOMER_SERVICE",
	}
	RoleType_value = map[string]int32{
		"ROLE_NORMAL":           0,
		"ROLE_ADMIN":            1,
		"ROLE_CUSTOMER_SERVICE": 2,
	}
)

func (x RoleType) Enum() *RoleType {
	p := new(RoleType)
	*p = x
	return p
}

func (x RoleType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoleType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_protocol_v1_common_proto_enumTypes[2].Descriptor()
}

func (RoleType) Type() protoreflect.EnumType {
	return &file_api_protocol_v1_common_proto_enumTypes[2]
}

func (x RoleType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoleType.Descriptor instead.
func (RoleType) EnumDescriptor() ([]byte, []int) {
	return file_api_protocol_v1_common_proto_rawDescGZIP(), []int{2}
}

type MsgType int32

const (
	MsgType_MSG_SINGLE        MsgType = 0 //单聊
	MsgType_MSG_GROUP         MsgType = 1 //群聊
	MsgType_MSG_CHATROOM      MsgType = 2 //聊天室
	MsgType_MSG_VIRTUAL_GROUP MsgType = 3 //虚拟组
	MsgType_MSG_APPLICATION   MsgType = 4 //应用通知类
)

// Enum value maps for MsgType.
var (
	MsgType_name = map[int32]string{
		0: "MSG_SINGLE",
		1: "MSG_GROUP",
		2: "MSG_CHATROOM",
		3: "MSG_VIRTUAL_GROUP",
		4: "MSG_APPLICATION",
	}
	MsgType_value = map[string]int32{
		"MSG_SINGLE":        0,
		"MSG_GROUP":         1,
		"MSG_CHATROOM":      2,
		"MSG_VIRTUAL_GROUP": 3,
		"MSG_APPLICATION":   4,
	}
)

func (x MsgType) Enum() *MsgType {
	p := new(MsgType)
	*p = x
	return p
}

func (x MsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_protocol_v1_common_proto_enumTypes[3].Descriptor()
}

func (MsgType) Type() protoreflect.EnumType {
	return &file_api_protocol_v1_common_proto_enumTypes[3]
}

func (x MsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgType.Descriptor instead.
func (MsgType) EnumDescriptor() ([]byte, []int) {
	return file_api_protocol_v1_common_proto_rawDescGZIP(), []int{3}
}

type UserType int32

const (
	UserType_USER_NORMAL        UserType = 0 //普通用户
	UserType_USER_VIRTUAL_GROUP UserType = 1 //虚拟组用户
	UserType_USER_SYSTEM        UserType = 2 //系统用户
	UserType_USER_APPLICATION   UserType = 3 //应用用户
)

// Enum value maps for UserType.
var (
	UserType_name = map[int32]string{
		0: "USER_NORMAL",
		1: "USER_VIRTUAL_GROUP",
		2: "USER_SYSTEM",
		3: "USER_APPLICATION",
	}
	UserType_value = map[string]int32{
		"USER_NORMAL":        0,
		"USER_VIRTUAL_GROUP": 1,
		"USER_SYSTEM":        2,
		"USER_APPLICATION":   3,
	}
)

func (x UserType) Enum() *UserType {
	p := new(UserType)
	*p = x
	return p
}

func (x UserType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_protocol_v1_common_proto_enumTypes[4].Descriptor()
}

func (UserType) Type() protoreflect.EnumType {
	return &file_api_protocol_v1_common_proto_enumTypes[4]
}

func (x UserType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserType.Descriptor instead.
func (UserType) EnumDescriptor() ([]byte, []int) {
	return file_api_protocol_v1_common_proto_rawDescGZIP(), []int{4}
}

var File_api_protocol_v1_common_proto protoreflect.FileDescriptor

var file_api_protocol_v1_common_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x76,
	0x31, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x76, 0x31, 0x2a, 0x47, 0x0a, 0x0a, 0x44,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x07, 0x0a, 0x03, 0x49, 0x4f, 0x53,
	0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x41, 0x4e, 0x44, 0x52, 0x4f, 0x49, 0x44, 0x10, 0x01, 0x12,
	0x07, 0x0a, 0x03, 0x57, 0x45, 0x42, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x4d, 0x49, 0x4e, 0x49,
	0x57, 0x45, 0x43, 0x48, 0x41, 0x54, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x55, 0x4e, 0x4b, 0x4e,
	0x4f, 0x57, 0x10, 0x09, 0x2a, 0x21, 0x0a, 0x09, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x0a, 0x0a, 0x06, 0x4d, 0x41, 0x4e, 0x55, 0x41, 0x4c, 0x10, 0x00, 0x12, 0x08, 0x0a,
	0x04, 0x41, 0x55, 0x54, 0x4f, 0x10, 0x01, 0x2a, 0x46, 0x0a, 0x08, 0x52, 0x6f, 0x6c, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x52, 0x4f, 0x4c, 0x45, 0x5f, 0x4e, 0x4f, 0x52, 0x4d,
	0x41, 0x4c, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x52, 0x4f, 0x4c, 0x45, 0x5f, 0x41, 0x44, 0x4d,
	0x49, 0x4e, 0x10, 0x01, 0x12, 0x19, 0x0a, 0x15, 0x52, 0x4f, 0x4c, 0x45, 0x5f, 0x43, 0x55, 0x53,
	0x54, 0x4f, 0x4d, 0x45, 0x52, 0x5f, 0x53, 0x45, 0x52, 0x56, 0x49, 0x43, 0x45, 0x10, 0x02, 0x2a,
	0x66, 0x0a, 0x07, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x0a, 0x4d, 0x53,
	0x47, 0x5f, 0x53, 0x49, 0x4e, 0x47, 0x4c, 0x45, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x4d, 0x53,
	0x47, 0x5f, 0x47, 0x52, 0x4f, 0x55, 0x50, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x4d, 0x53, 0x47,
	0x5f, 0x43, 0x48, 0x41, 0x54, 0x52, 0x4f, 0x4f, 0x4d, 0x10, 0x02, 0x12, 0x15, 0x0a, 0x11, 0x4d,
	0x53, 0x47, 0x5f, 0x56, 0x49, 0x52, 0x54, 0x55, 0x41, 0x4c, 0x5f, 0x47, 0x52, 0x4f, 0x55, 0x50,
	0x10, 0x03, 0x12, 0x13, 0x0a, 0x0f, 0x4d, 0x53, 0x47, 0x5f, 0x41, 0x50, 0x50, 0x4c, 0x49, 0x43,
	0x41, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x04, 0x2a, 0x5a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x4e, 0x4f, 0x52, 0x4d,
	0x41, 0x4c, 0x10, 0x00, 0x12, 0x16, 0x0a, 0x12, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x56, 0x49, 0x52,
	0x54, 0x55, 0x41, 0x4c, 0x5f, 0x47, 0x52, 0x4f, 0x55, 0x50, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b,
	0x55, 0x53, 0x45, 0x52, 0x5f, 0x53, 0x59, 0x53, 0x54, 0x45, 0x4d, 0x10, 0x02, 0x12, 0x14, 0x0a,
	0x10, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x41, 0x50, 0x50, 0x4c, 0x49, 0x43, 0x41, 0x54, 0x49, 0x4f,
	0x4e, 0x10, 0x03, 0x42, 0x38, 0x0a, 0x0b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e,
	0x76, 0x31, 0x50, 0x01, 0x5a, 0x1a, 0x78, 0x68, 0x61, 0x70, 0x70, 0x65, 0x6e, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31,
	0xa2, 0x02, 0x0a, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x56, 0x31, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_protocol_v1_common_proto_rawDescOnce sync.Once
	file_api_protocol_v1_common_proto_rawDescData = file_api_protocol_v1_common_proto_rawDesc
)

func file_api_protocol_v1_common_proto_rawDescGZIP() []byte {
	file_api_protocol_v1_common_proto_rawDescOnce.Do(func() {
		file_api_protocol_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_protocol_v1_common_proto_rawDescData)
	})
	return file_api_protocol_v1_common_proto_rawDescData
}

var file_api_protocol_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_api_protocol_v1_common_proto_goTypes = []interface{}{
	(DeviceType)(0), // 0: protocol.v1.DeviceType
	(LoginType)(0),  // 1: protocol.v1.LoginType
	(RoleType)(0),   // 2: protocol.v1.RoleType
	(MsgType)(0),    // 3: protocol.v1.MsgType
	(UserType)(0),   // 4: protocol.v1.UserType
}
var file_api_protocol_v1_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_protocol_v1_common_proto_init() }
func file_api_protocol_v1_common_proto_init() {
	if File_api_protocol_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_protocol_v1_common_proto_rawDesc,
			NumEnums:      5,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_protocol_v1_common_proto_goTypes,
		DependencyIndexes: file_api_protocol_v1_common_proto_depIdxs,
		EnumInfos:         file_api_protocol_v1_common_proto_enumTypes,
	}.Build()
	File_api_protocol_v1_common_proto = out.File
	file_api_protocol_v1_common_proto_rawDesc = nil
	file_api_protocol_v1_common_proto_goTypes = nil
	file_api_protocol_v1_common_proto_depIdxs = nil
}
