// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.15.6
// source: api/portal/v1/basic.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBasicConfigRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId string `protobuf:"bytes,1,opt,name=clientId,proto3" json:"clientId,omitempty"`
}

func (x *GetBasicConfigRequest) Reset() {
	*x = GetBasicConfigRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_portal_v1_basic_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBasicConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBasicConfigRequest) ProtoMessage() {}

func (x *GetBasicConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_portal_v1_basic_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBasicConfigRequest.ProtoReflect.Descriptor instead.
func (*GetBasicConfigRequest) Descriptor() ([]byte, []int) {
	return file_api_portal_v1_basic_proto_rawDescGZIP(), []int{0}
}

func (x *GetBasicConfigRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type GetBasicConfigReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SocketHost     string `protobuf:"bytes,1,opt,name=socketHost,proto3" json:"socketHost,omitempty"`
	FileServerHost string `protobuf:"bytes,2,opt,name=fileServerHost,proto3" json:"fileServerHost,omitempty"`
}

func (x *GetBasicConfigReply) Reset() {
	*x = GetBasicConfigReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_portal_v1_basic_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBasicConfigReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBasicConfigReply) ProtoMessage() {}

func (x *GetBasicConfigReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_portal_v1_basic_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBasicConfigReply.ProtoReflect.Descriptor instead.
func (*GetBasicConfigReply) Descriptor() ([]byte, []int) {
	return file_api_portal_v1_basic_proto_rawDescGZIP(), []int{1}
}

func (x *GetBasicConfigReply) GetSocketHost() string {
	if x != nil {
		return x.SocketHost
	}
	return ""
}

func (x *GetBasicConfigReply) GetFileServerHost() string {
	if x != nil {
		return x.FileServerHost
	}
	return ""
}

type GetSocketHostConfigRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId string `protobuf:"bytes,1,opt,name=clientId,proto3" json:"clientId,omitempty"`
	UserId   uint64 `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *GetSocketHostConfigRequest) Reset() {
	*x = GetSocketHostConfigRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_portal_v1_basic_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSocketHostConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSocketHostConfigRequest) ProtoMessage() {}

func (x *GetSocketHostConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_portal_v1_basic_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSocketHostConfigRequest.ProtoReflect.Descriptor instead.
func (*GetSocketHostConfigRequest) Descriptor() ([]byte, []int) {
	return file_api_portal_v1_basic_proto_rawDescGZIP(), []int{2}
}

func (x *GetSocketHostConfigRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *GetSocketHostConfigRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetSocketHostConfigReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SocketHost string `protobuf:"bytes,1,opt,name=socketHost,proto3" json:"socketHost,omitempty"`
}

func (x *GetSocketHostConfigReply) Reset() {
	*x = GetSocketHostConfigReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_portal_v1_basic_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSocketHostConfigReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSocketHostConfigReply) ProtoMessage() {}

func (x *GetSocketHostConfigReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_portal_v1_basic_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSocketHostConfigReply.ProtoReflect.Descriptor instead.
func (*GetSocketHostConfigReply) Descriptor() ([]byte, []int) {
	return file_api_portal_v1_basic_proto_rawDescGZIP(), []int{3}
}

func (x *GetSocketHostConfigReply) GetSocketHost() string {
	if x != nil {
		return x.SocketHost
	}
	return ""
}

var File_api_portal_v1_basic_proto protoreflect.FileDescriptor

var file_api_portal_v1_basic_proto_rawDesc = []byte{
	0x0a, 0x19, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x2f, 0x76, 0x31, 0x2f,
	0x62, 0x61, 0x73, 0x69, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x70, 0x6f, 0x72,
	0x74, 0x61, 0x6c, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76,
	0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3e, 0x0a,
	0x15, 0x47, 0x65, 0x74, 0x42, 0x61, 0x73, 0x69, 0x63, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x09, 0xfa, 0x42, 0x06, 0x72, 0x04, 0x10,
	0x18, 0x18, 0x24, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x5d, 0x0a,
	0x13, 0x47, 0x65, 0x74, 0x42, 0x61, 0x73, 0x69, 0x63, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x48, 0x6f,
	0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x6f, 0x63, 0x6b, 0x65, 0x74,
	0x48, 0x6f, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x0e, 0x66, 0x69, 0x6c, 0x65, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x48, 0x6f, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x66, 0x69,
	0x6c, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x48, 0x6f, 0x73, 0x74, 0x22, 0x5b, 0x0a, 0x1a,
	0x47, 0x65, 0x74, 0x53, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x48, 0x6f, 0x73, 0x74, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x08, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x09, 0xfa, 0x42,
	0x06, 0x72, 0x04, 0x10, 0x18, 0x18, 0x24, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x3a, 0x0a, 0x18, 0x47, 0x65, 0x74,
	0x53, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x48, 0x6f, 0x73, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x48,
	0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x6f, 0x63, 0x6b, 0x65,
	0x74, 0x48, 0x6f, 0x73, 0x74, 0x32, 0xde, 0x01, 0x0a, 0x06, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x12, 0x6f, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x42, 0x61, 0x73, 0x69, 0x63, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x12, 0x20, 0x2e, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x47,
	0x65, 0x74, 0x42, 0x61, 0x73, 0x69, 0x63, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x2e, 0x76, 0x31,
	0x2e, 0x47, 0x65, 0x74, 0x42, 0x61, 0x73, 0x69, 0x63, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x1b, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x15, 0x3a, 0x01, 0x2a, 0x22,
	0x10, 0x2f, 0x62, 0x61, 0x73, 0x69, 0x63, 0x2f, 0x67, 0x65, 0x74, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x12, 0x63, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x53, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x48, 0x6f,
	0x73, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x25, 0x2e, 0x70, 0x6f, 0x72, 0x74, 0x61,
	0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x48, 0x6f,
	0x73, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x23, 0x2e, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x53,
	0x6f, 0x63, 0x6b, 0x65, 0x74, 0x48, 0x6f, 0x73, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x32, 0x0a, 0x09, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6c,
	0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a, 0x18, 0x78, 0x68, 0x61, 0x70, 0x70, 0x65, 0x6e, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0xa2,
	0x02, 0x08, 0x50, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_api_portal_v1_basic_proto_rawDescOnce sync.Once
	file_api_portal_v1_basic_proto_rawDescData = file_api_portal_v1_basic_proto_rawDesc
)

func file_api_portal_v1_basic_proto_rawDescGZIP() []byte {
	file_api_portal_v1_basic_proto_rawDescOnce.Do(func() {
		file_api_portal_v1_basic_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_portal_v1_basic_proto_rawDescData)
	})
	return file_api_portal_v1_basic_proto_rawDescData
}

var file_api_portal_v1_basic_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_portal_v1_basic_proto_goTypes = []interface{}{
	(*GetBasicConfigRequest)(nil),      // 0: portal.v1.GetBasicConfigRequest
	(*GetBasicConfigReply)(nil),        // 1: portal.v1.GetBasicConfigReply
	(*GetSocketHostConfigRequest)(nil), // 2: portal.v1.GetSocketHostConfigRequest
	(*GetSocketHostConfigReply)(nil),   // 3: portal.v1.GetSocketHostConfigReply
}
var file_api_portal_v1_basic_proto_depIdxs = []int32{
	0, // 0: portal.v1.Config.GetBasicConfig:input_type -> portal.v1.GetBasicConfigRequest
	2, // 1: portal.v1.Config.GetSocketHostConfig:input_type -> portal.v1.GetSocketHostConfigRequest
	1, // 2: portal.v1.Config.GetBasicConfig:output_type -> portal.v1.GetBasicConfigReply
	3, // 3: portal.v1.Config.GetSocketHostConfig:output_type -> portal.v1.GetSocketHostConfigReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_portal_v1_basic_proto_init() }
func file_api_portal_v1_basic_proto_init() {
	if File_api_portal_v1_basic_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_portal_v1_basic_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBasicConfigRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_portal_v1_basic_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBasicConfigReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_portal_v1_basic_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSocketHostConfigRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_portal_v1_basic_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSocketHostConfigReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_portal_v1_basic_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_portal_v1_basic_proto_goTypes,
		DependencyIndexes: file_api_portal_v1_basic_proto_depIdxs,
		MessageInfos:      file_api_portal_v1_basic_proto_msgTypes,
	}.Build()
	File_api_portal_v1_basic_proto = out.File
	file_api_portal_v1_basic_proto_rawDesc = nil
	file_api_portal_v1_basic_proto_goTypes = nil
	file_api_portal_v1_basic_proto_depIdxs = nil
}
