// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.7.2
// - protoc             v3.15.6
// source: api/portal/v1/basic.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationConfigGetBasicConfig = "/portal.v1.Config/GetBasicConfig"

type ConfigHTTPServer interface {
	// GetBasicConfig 获取基础配置
	GetBasicConfig(context.Context, *GetBasicConfigRequest) (*GetBasicConfigReply, error)
}

func RegisterConfigHTTPServer(s *http.Server, srv ConfigHTTPServer) {
	r := s.Route("/")
	r.POST("/basic/config", _Config_GetBasicConfig0_HTTP_Handler(srv))
}

func _Config_GetBasicConfig0_HTTP_Handler(srv ConfigHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetBasicConfigRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationConfigGetBasicConfig)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetBasicConfig(ctx, req.(*GetBasicConfigRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetBasicConfigReply)
		return ctx.Result(200, reply)
	}
}

type ConfigHTTPClient interface {
	GetBasicConfig(ctx context.Context, req *GetBasicConfigRequest, opts ...http.CallOption) (rsp *GetBasicConfigReply, err error)
}

type ConfigHTTPClientImpl struct {
	cc *http.Client
}

func NewConfigHTTPClient(client *http.Client) ConfigHTTPClient {
	return &ConfigHTTPClientImpl{client}
}

func (c *ConfigHTTPClientImpl) GetBasicConfig(ctx context.Context, in *GetBasicConfigRequest, opts ...http.CallOption) (*GetBasicConfigReply, error) {
	var out GetBasicConfigReply
	pattern := "/basic/config"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationConfigGetBasicConfig))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
