// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: api/portal/v1/service.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	v1 "xhappen/api/basic/v1"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SMSCodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *SMSCodeRequest) Reset() {
	*x = SMSCodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_portal_v1_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SMSCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SMSCodeRequest) ProtoMessage() {}

func (x *SMSCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_portal_v1_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SMSCodeRequest.ProtoReflect.Descriptor instead.
func (*SMSCodeRequest) Descriptor() ([]byte, []int) {
	return file_api_portal_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *SMSCodeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SMSCodeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SMSCodeReply) Reset() {
	*x = SMSCodeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_portal_v1_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SMSCodeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SMSCodeReply) ProtoMessage() {}

func (x *SMSCodeReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_portal_v1_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SMSCodeReply.ProtoReflect.Descriptor instead.
func (*SMSCodeReply) Descriptor() ([]byte, []int) {
	return file_api_portal_v1_service_proto_rawDescGZIP(), []int{1}
}

type LoginByMobileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mobile  string `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	SmsCode string `protobuf:"bytes,2,opt,name=smsCode,proto3" json:"smsCode,omitempty"`
}

func (x *LoginByMobileRequest) Reset() {
	*x = LoginByMobileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_portal_v1_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginByMobileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginByMobileRequest) ProtoMessage() {}

func (x *LoginByMobileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_portal_v1_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginByMobileRequest.ProtoReflect.Descriptor instead.
func (*LoginByMobileRequest) Descriptor() ([]byte, []int) {
	return file_api_portal_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *LoginByMobileRequest) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *LoginByMobileRequest) GetSmsCode() string {
	if x != nil {
		return x.SmsCode
	}
	return ""
}

type LoginByMobileReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	User  *v1.User `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *LoginByMobileReply) Reset() {
	*x = LoginByMobileReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_portal_v1_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginByMobileReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginByMobileReply) ProtoMessage() {}

func (x *LoginByMobileReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_portal_v1_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginByMobileReply.ProtoReflect.Descriptor instead.
func (*LoginByMobileReply) Descriptor() ([]byte, []int) {
	return file_api_portal_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *LoginByMobileReply) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginByMobileReply) GetUser() *v1.User {
	if x != nil {
		return x.User
	}
	return nil
}

var File_api_portal_v1_service_proto protoreflect.FileDescriptor

var file_api_portal_v1_service_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x2f, 0x76, 0x31, 0x2f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x70,
	0x6f, 0x72, 0x74, 0x61, 0x6c, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x18, 0x61, 0x70, 0x69, 0x2f, 0x62, 0x61, 0x73, 0x69,
	0x63, 0x2f, 0x76, 0x31, 0x2f, 0x62, 0x61, 0x73, 0x69, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x24, 0x0a, 0x0e, 0x53, 0x4d, 0x53, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x0e, 0x0a, 0x0c, 0x53, 0x4d, 0x53, 0x43, 0x6f, 0x64,
	0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x48, 0x0a, 0x14, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x42,
	0x79, 0x4d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x6d, 0x73, 0x43, 0x6f, 0x64,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x6d, 0x73, 0x43, 0x6f, 0x64, 0x65,
	0x22, 0x4e, 0x0a, 0x12, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x42, 0x79, 0x4d, 0x6f, 0x62, 0x69, 0x6c,
	0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x22, 0x0a, 0x04,
	0x75, 0x73, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x62, 0x61, 0x73,
	0x69, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72,
	0x32, 0xcc, 0x01, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x5b, 0x0a, 0x0b, 0x53, 0x65, 0x6e,
	0x64, 0x53, 0x4d, 0x53, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x19, 0x2e, 0x70, 0x6f, 0x72, 0x74, 0x61,
	0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x4d, 0x53, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x2e, 0x76, 0x31, 0x2e,
	0x53, 0x4d, 0x53, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x18, 0x82, 0xd3,
	0xe4, 0x93, 0x02, 0x12, 0x22, 0x0d, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x73, 0x6d, 0x73, 0x63,
	0x6f, 0x64, 0x65, 0x3a, 0x01, 0x2a, 0x12, 0x67, 0x0a, 0x0d, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x42,
	0x79, 0x4d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x12, 0x1f, 0x2e, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6c,
	0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x42, 0x79, 0x4d, 0x6f, 0x62, 0x69, 0x6c,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x70, 0x6f, 0x72, 0x74, 0x61,
	0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x42, 0x79, 0x4d, 0x6f, 0x62, 0x69,
	0x6c, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x16, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x10, 0x22,
	0x0b, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x3a, 0x01, 0x2a, 0x42,
	0x1a, 0x5a, 0x18, 0x78, 0x68, 0x61, 0x70, 0x70, 0x65, 0x6e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70,
	0x6f, 0x72, 0x74, 0x61, 0x6c, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_api_portal_v1_service_proto_rawDescOnce sync.Once
	file_api_portal_v1_service_proto_rawDescData = file_api_portal_v1_service_proto_rawDesc
)

func file_api_portal_v1_service_proto_rawDescGZIP() []byte {
	file_api_portal_v1_service_proto_rawDescOnce.Do(func() {
		file_api_portal_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_portal_v1_service_proto_rawDescData)
	})
	return file_api_portal_v1_service_proto_rawDescData
}

var file_api_portal_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_portal_v1_service_proto_goTypes = []interface{}{
	(*SMSCodeRequest)(nil),       // 0: portal.v1.SMSCodeRequest
	(*SMSCodeReply)(nil),         // 1: portal.v1.SMSCodeReply
	(*LoginByMobileRequest)(nil), // 2: portal.v1.LoginByMobileRequest
	(*LoginByMobileReply)(nil),   // 3: portal.v1.LoginByMobileReply
	(*v1.User)(nil),              // 4: basic.v1.User
}
var file_api_portal_v1_service_proto_depIdxs = []int32{
	4, // 0: portal.v1.LoginByMobileReply.user:type_name -> basic.v1.User
	0, // 1: portal.v1.User.SendSMSCode:input_type -> portal.v1.SMSCodeRequest
	2, // 2: portal.v1.User.LoginByMobile:input_type -> portal.v1.LoginByMobileRequest
	1, // 3: portal.v1.User.SendSMSCode:output_type -> portal.v1.SMSCodeReply
	3, // 4: portal.v1.User.LoginByMobile:output_type -> portal.v1.LoginByMobileReply
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_portal_v1_service_proto_init() }
func file_api_portal_v1_service_proto_init() {
	if File_api_portal_v1_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_portal_v1_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SMSCodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_portal_v1_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SMSCodeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_portal_v1_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginByMobileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_portal_v1_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginByMobileReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_portal_v1_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_portal_v1_service_proto_goTypes,
		DependencyIndexes: file_api_portal_v1_service_proto_depIdxs,
		MessageInfos:      file_api_portal_v1_service_proto_msgTypes,
	}.Build()
	File_api_portal_v1_service_proto = out.File
	file_api_portal_v1_service_proto_rawDesc = nil
	file_api_portal_v1_service_proto_goTypes = nil
	file_api_portal_v1_service_proto_depIdxs = nil
}
