// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// protoc-gen-go-http v2.2.2

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

type UserHTTPServer interface {
	DeRegister(context.Context, *DeRegisterRequest) (*DeRegisterReply, error)
	GetSelfProfile(context.Context, *GetSelfProfileRequest) (*GetSelfProfileReply, error)
	GetUserProfile(context.Context, *GetUserProfileRequest) (*GetUserProfileReply, error)
	LoginByMobile(context.Context, *LoginByMobileRequest) (*LoginByMobileReply, error)
	Logout(context.Context, *LogoutRequest) (*LogoutReply, error)
	SendSMSCode(context.Context, *SMSCodeRequest) (*SMSCodeReply, error)
}

func RegisterUserHTTPServer(s *http.Server, srv UserHTTPServer) {
	r := s.Route("/")
	r.POST("/user/smscode", _User_SendSMSCode0_HTTP_Handler(srv))
	r.POST("/user/login", _User_LoginByMobile0_HTTP_Handler(srv))
	r.POST("/auth/user/logout", _User_Logout0_HTTP_Handler(srv))
	r.POST("/auth/user/deregister", _User_DeRegister0_HTTP_Handler(srv))
	r.POST("/user/getprofile", _User_GetUserProfile0_HTTP_Handler(srv))
	r.POST("/auth/user/getselfprofile", _User_GetSelfProfile0_HTTP_Handler(srv))
}

func _User_SendSMSCode0_HTTP_Handler(srv UserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SMSCodeRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/portal.v1.User/SendSMSCode")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SendSMSCode(ctx, req.(*SMSCodeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SMSCodeReply)
		return ctx.Result(200, reply)
	}
}

func _User_LoginByMobile0_HTTP_Handler(srv UserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in LoginByMobileRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/portal.v1.User/LoginByMobile")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.LoginByMobile(ctx, req.(*LoginByMobileRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*LoginByMobileReply)
		return ctx.Result(200, reply)
	}
}

func _User_Logout0_HTTP_Handler(srv UserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in LogoutRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/portal.v1.User/Logout")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Logout(ctx, req.(*LogoutRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*LogoutReply)
		return ctx.Result(200, reply)
	}
}

func _User_DeRegister0_HTTP_Handler(srv UserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeRegisterRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/portal.v1.User/DeRegister")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeRegister(ctx, req.(*DeRegisterRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeRegisterReply)
		return ctx.Result(200, reply)
	}
}

func _User_GetUserProfile0_HTTP_Handler(srv UserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetUserProfileRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/portal.v1.User/GetUserProfile")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetUserProfile(ctx, req.(*GetUserProfileRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetUserProfileReply)
		return ctx.Result(200, reply)
	}
}

func _User_GetSelfProfile0_HTTP_Handler(srv UserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetSelfProfileRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/portal.v1.User/GetSelfProfile")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetSelfProfile(ctx, req.(*GetSelfProfileRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetSelfProfileReply)
		return ctx.Result(200, reply)
	}
}

type UserHTTPClient interface {
	DeRegister(ctx context.Context, req *DeRegisterRequest, opts ...http.CallOption) (rsp *DeRegisterReply, err error)
	GetSelfProfile(ctx context.Context, req *GetSelfProfileRequest, opts ...http.CallOption) (rsp *GetSelfProfileReply, err error)
	GetUserProfile(ctx context.Context, req *GetUserProfileRequest, opts ...http.CallOption) (rsp *GetUserProfileReply, err error)
	LoginByMobile(ctx context.Context, req *LoginByMobileRequest, opts ...http.CallOption) (rsp *LoginByMobileReply, err error)
	Logout(ctx context.Context, req *LogoutRequest, opts ...http.CallOption) (rsp *LogoutReply, err error)
	SendSMSCode(ctx context.Context, req *SMSCodeRequest, opts ...http.CallOption) (rsp *SMSCodeReply, err error)
}

type UserHTTPClientImpl struct {
	cc *http.Client
}

func NewUserHTTPClient(client *http.Client) UserHTTPClient {
	return &UserHTTPClientImpl{client}
}

func (c *UserHTTPClientImpl) DeRegister(ctx context.Context, in *DeRegisterRequest, opts ...http.CallOption) (*DeRegisterReply, error) {
	var out DeRegisterReply
	pattern := "/auth/user/deregister"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation("/portal.v1.User/DeRegister"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *UserHTTPClientImpl) GetSelfProfile(ctx context.Context, in *GetSelfProfileRequest, opts ...http.CallOption) (*GetSelfProfileReply, error) {
	var out GetSelfProfileReply
	pattern := "/auth/user/getselfprofile"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation("/portal.v1.User/GetSelfProfile"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *UserHTTPClientImpl) GetUserProfile(ctx context.Context, in *GetUserProfileRequest, opts ...http.CallOption) (*GetUserProfileReply, error) {
	var out GetUserProfileReply
	pattern := "/user/getprofile"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation("/portal.v1.User/GetUserProfile"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *UserHTTPClientImpl) LoginByMobile(ctx context.Context, in *LoginByMobileRequest, opts ...http.CallOption) (*LoginByMobileReply, error) {
	var out LoginByMobileReply
	pattern := "/user/login"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation("/portal.v1.User/LoginByMobile"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *UserHTTPClientImpl) Logout(ctx context.Context, in *LogoutRequest, opts ...http.CallOption) (*LogoutReply, error) {
	var out LogoutReply
	pattern := "/auth/user/logout"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation("/portal.v1.User/Logout"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *UserHTTPClientImpl) SendSMSCode(ctx context.Context, in *SMSCodeRequest, opts ...http.CallOption) (*SMSCodeReply, error) {
	var out SMSCodeReply
	pattern := "/user/smscode"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation("/portal.v1.User/SendSMSCode"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
