// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: api/basic/v1/error_reason.proto

package v1

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorReason int32

const (
	ErrorReason_UNKNOWN            ErrorReason = 0
	ErrorReason_SERBER_UNAVAILABLE ErrorReason = 1
	ErrorReason_REQUEST_TOO_FAST   ErrorReason = 2
	ErrorReason_TIME_OUT           ErrorReason = 3
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0: "UNKNOWN",
		1: "SERBER_UNAVAILABLE",
		2: "REQUEST_TOO_FAST",
		3: "TIME_OUT",
	}
	ErrorReason_value = map[string]int32{
		"UNKNOWN":            0,
		"SERBER_UNAVAILABLE": 1,
		"REQUEST_TOO_FAST":   2,
		"TIME_OUT":           3,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_api_basic_v1_error_reason_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_api_basic_v1_error_reason_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_api_basic_v1_error_reason_proto_rawDescGZIP(), []int{0}
}

type ErrorUserReason int32

const (
	ErrorUserReason_AUTH_CODE_INVALID ErrorUserReason = 0
	ErrorUserReason_BLACK_USER        ErrorUserReason = 1
)

// Enum value maps for ErrorUserReason.
var (
	ErrorUserReason_name = map[int32]string{
		0: "AUTH_CODE_INVALID",
		1: "BLACK_USER",
	}
	ErrorUserReason_value = map[string]int32{
		"AUTH_CODE_INVALID": 0,
		"BLACK_USER":        1,
	}
)

func (x ErrorUserReason) Enum() *ErrorUserReason {
	p := new(ErrorUserReason)
	*p = x
	return p
}

func (x ErrorUserReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorUserReason) Descriptor() protoreflect.EnumDescriptor {
	return file_api_basic_v1_error_reason_proto_enumTypes[1].Descriptor()
}

func (ErrorUserReason) Type() protoreflect.EnumType {
	return &file_api_basic_v1_error_reason_proto_enumTypes[1]
}

func (x ErrorUserReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorUserReason.Descriptor instead.
func (ErrorUserReason) EnumDescriptor() ([]byte, []int) {
	return file_api_basic_v1_error_reason_proto_rawDescGZIP(), []int{1}
}

type ErrorSocketBindReason int32

const (
	ErrorSocketBindReason_CLIENTID_REJECTED ErrorSocketBindReason = 0
	ErrorSocketBindReason_UPGRADE           ErrorSocketBindReason = 1
	ErrorSocketBindReason_LOGINED           ErrorSocketBindReason = 2
	ErrorSocketBindReason_SWITH_HOST        ErrorSocketBindReason = 3
	ErrorSocketBindReason_BLACK_DEVICE      ErrorSocketBindReason = 4
)

// Enum value maps for ErrorSocketBindReason.
var (
	ErrorSocketBindReason_name = map[int32]string{
		0: "CLIENTID_REJECTED",
		1: "UPGRADE",
		2: "LOGINED",
		3: "SWITH_HOST",
		4: "BLACK_DEVICE",
	}
	ErrorSocketBindReason_value = map[string]int32{
		"CLIENTID_REJECTED": 0,
		"UPGRADE":           1,
		"LOGINED":           2,
		"SWITH_HOST":        3,
		"BLACK_DEVICE":      4,
	}
)

func (x ErrorSocketBindReason) Enum() *ErrorSocketBindReason {
	p := new(ErrorSocketBindReason)
	*p = x
	return p
}

func (x ErrorSocketBindReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorSocketBindReason) Descriptor() protoreflect.EnumDescriptor {
	return file_api_basic_v1_error_reason_proto_enumTypes[2].Descriptor()
}

func (ErrorSocketBindReason) Type() protoreflect.EnumType {
	return &file_api_basic_v1_error_reason_proto_enumTypes[2]
}

func (x ErrorSocketBindReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorSocketBindReason.Descriptor instead.
func (ErrorSocketBindReason) EnumDescriptor() ([]byte, []int) {
	return file_api_basic_v1_error_reason_proto_rawDescGZIP(), []int{2}
}

type ErrorSocketAuthReason int32

const (
	ErrorSocketAuthReason_TOKEN_EXPIRE ErrorSocketAuthReason = 0
)

// Enum value maps for ErrorSocketAuthReason.
var (
	ErrorSocketAuthReason_name = map[int32]string{
		0: "TOKEN_EXPIRE",
	}
	ErrorSocketAuthReason_value = map[string]int32{
		"TOKEN_EXPIRE": 0,
	}
)

func (x ErrorSocketAuthReason) Enum() *ErrorSocketAuthReason {
	p := new(ErrorSocketAuthReason)
	*p = x
	return p
}

func (x ErrorSocketAuthReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorSocketAuthReason) Descriptor() protoreflect.EnumDescriptor {
	return file_api_basic_v1_error_reason_proto_enumTypes[3].Descriptor()
}

func (ErrorSocketAuthReason) Type() protoreflect.EnumType {
	return &file_api_basic_v1_error_reason_proto_enumTypes[3]
}

func (x ErrorSocketAuthReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorSocketAuthReason.Descriptor instead.
func (ErrorSocketAuthReason) EnumDescriptor() ([]byte, []int) {
	return file_api_basic_v1_error_reason_proto_rawDescGZIP(), []int{3}
}

var File_api_basic_v1_error_reason_proto protoreflect.FileDescriptor

var file_api_basic_v1_error_reason_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x61, 0x70, 0x69, 0x2f, 0x62, 0x61, 0x73, 0x69, 0x63, 0x2f, 0x76, 0x31, 0x2f, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x5f, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x08, 0x62, 0x61, 0x73, 0x69, 0x63, 0x2e, 0x76, 0x31, 0x1a, 0x13, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x73, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2a, 0x74, 0x0a, 0x0b, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12,
	0x11, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x1a, 0x04, 0xa8, 0x45,
	0x9a, 0x03, 0x12, 0x1c, 0x0a, 0x12, 0x53, 0x45, 0x52, 0x42, 0x45, 0x52, 0x5f, 0x55, 0x4e, 0x41,
	0x56, 0x41, 0x49, 0x4c, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x01, 0x1a, 0x04, 0xa8, 0x45, 0x9b, 0x03,
	0x12, 0x1a, 0x0a, 0x10, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x5f, 0x54, 0x4f, 0x4f, 0x5f,
	0x46, 0x41, 0x53, 0x54, 0x10, 0x02, 0x1a, 0x04, 0xa8, 0x45, 0x9c, 0x03, 0x12, 0x12, 0x0a, 0x08,
	0x54, 0x49, 0x4d, 0x45, 0x5f, 0x4f, 0x55, 0x54, 0x10, 0x03, 0x1a, 0x04, 0xa8, 0x45, 0x9d, 0x03,
	0x1a, 0x04, 0xa0, 0x45, 0xf4, 0x03, 0x2a, 0x4a, 0x0a, 0x0f, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x55,
	0x73, 0x65, 0x72, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x11, 0x41, 0x55, 0x54,
	0x48, 0x5f, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x10, 0x00,
	0x1a, 0x04, 0xa8, 0x45, 0xb8, 0x03, 0x12, 0x14, 0x0a, 0x0a, 0x42, 0x4c, 0x41, 0x43, 0x4b, 0x5f,
	0x55, 0x53, 0x45, 0x52, 0x10, 0x01, 0x1a, 0x04, 0xa8, 0x45, 0xb9, 0x03, 0x1a, 0x04, 0xa0, 0x45,
	0xf4, 0x03, 0x2a, 0x8e, 0x01, 0x0a, 0x15, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x53, 0x6f, 0x63, 0x6b,
	0x65, 0x74, 0x42, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x11,
	0x43, 0x4c, 0x49, 0x45, 0x4e, 0x54, 0x49, 0x44, 0x5f, 0x52, 0x45, 0x4a, 0x45, 0x43, 0x54, 0x45,
	0x44, 0x10, 0x00, 0x1a, 0x04, 0xa8, 0x45, 0xa4, 0x03, 0x12, 0x11, 0x0a, 0x07, 0x55, 0x50, 0x47,
	0x52, 0x41, 0x44, 0x45, 0x10, 0x01, 0x1a, 0x04, 0xa8, 0x45, 0xa5, 0x03, 0x12, 0x11, 0x0a, 0x07,
	0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x45, 0x44, 0x10, 0x02, 0x1a, 0x04, 0xa8, 0x45, 0xa6, 0x03, 0x12,
	0x14, 0x0a, 0x0a, 0x53, 0x57, 0x49, 0x54, 0x48, 0x5f, 0x48, 0x4f, 0x53, 0x54, 0x10, 0x03, 0x1a,
	0x04, 0xa8, 0x45, 0xa7, 0x03, 0x12, 0x16, 0x0a, 0x0c, 0x42, 0x4c, 0x41, 0x43, 0x4b, 0x5f, 0x44,
	0x45, 0x56, 0x49, 0x43, 0x45, 0x10, 0x04, 0x1a, 0x04, 0xa8, 0x45, 0xa8, 0x03, 0x1a, 0x04, 0xa0,
	0x45, 0xf4, 0x03, 0x2a, 0x35, 0x0a, 0x15, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x53, 0x6f, 0x63, 0x6b,
	0x65, 0x74, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x0c,
	0x54, 0x4f, 0x4b, 0x45, 0x4e, 0x5f, 0x45, 0x58, 0x50, 0x49, 0x52, 0x45, 0x10, 0x00, 0x1a, 0x04,
	0xa8, 0x45, 0xae, 0x03, 0x1a, 0x04, 0xa0, 0x45, 0xf4, 0x03, 0x42, 0x30, 0x0a, 0x08, 0x62, 0x61,
	0x73, 0x69, 0x63, 0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a, 0x17, 0x78, 0x68, 0x61, 0x70, 0x70, 0x65,
	0x6e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x62, 0x61, 0x73, 0x69, 0x63, 0x2f, 0x76, 0x31, 0x3b, 0x76,
	0x31, 0xa2, 0x02, 0x08, 0x42, 0x61, 0x73, 0x69, 0x63, 0x6c, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_basic_v1_error_reason_proto_rawDescOnce sync.Once
	file_api_basic_v1_error_reason_proto_rawDescData = file_api_basic_v1_error_reason_proto_rawDesc
)

func file_api_basic_v1_error_reason_proto_rawDescGZIP() []byte {
	file_api_basic_v1_error_reason_proto_rawDescOnce.Do(func() {
		file_api_basic_v1_error_reason_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_basic_v1_error_reason_proto_rawDescData)
	})
	return file_api_basic_v1_error_reason_proto_rawDescData
}

var file_api_basic_v1_error_reason_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_api_basic_v1_error_reason_proto_goTypes = []interface{}{
	(ErrorReason)(0),           // 0: basic.v1.ErrorReason
	(ErrorUserReason)(0),       // 1: basic.v1.ErrorUserReason
	(ErrorSocketBindReason)(0), // 2: basic.v1.ErrorSocketBindReason
	(ErrorSocketAuthReason)(0), // 3: basic.v1.ErrorSocketAuthReason
}
var file_api_basic_v1_error_reason_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_basic_v1_error_reason_proto_init() }
func file_api_basic_v1_error_reason_proto_init() {
	if File_api_basic_v1_error_reason_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_basic_v1_error_reason_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_basic_v1_error_reason_proto_goTypes,
		DependencyIndexes: file_api_basic_v1_error_reason_proto_depIdxs,
		EnumInfos:         file_api_basic_v1_error_reason_proto_enumTypes,
	}.Build()
	File_api_basic_v1_error_reason_proto = out.File
	file_api_basic_v1_error_reason_proto_rawDesc = nil
	file_api_basic_v1_error_reason_proto_goTypes = nil
	file_api_basic_v1_error_reason_proto_depIdxs = nil
}
