trace:
  endpoint: http://127.0.0.1:14268/api/traces
server:
  grpc:
    addr: 0.0.0.0:9001
    timeout: 3s
  info:
    protoVersion: 1
    minSupportProtoVersion: 0
socket:
  main:
    tls: false
    tlsCert: 
    tlsKey: 
    tlsClientAuthPolicy:  
    tlsRootCAFile: 
    tcpAddress: ':8001'
    wsAddress: ':8002'
    minKeepAlive: 60s
    maxKeepAlive: 300s
    readBufferSize: 8192
    writeBufferSize: 8192
    writeTimeout: 1s
  queue:
    maxMsgSize: 65535
    maxRdyCount: 100
    syncEvery: 1
    msgTimeout: 5s
data:
  etcd:
    addr: 192.168.71.69:2379
    dialTimeout: 1s
    readTimeout: 1s
    writeTimeout: 1s

