server:
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
  info:
    capacity: 3
data:
  dms:
    addr: 192.168.71.69:27017
    username: root
    passwd: pwd9627
    database: xhappen
    idle: 10
    maxConns: 100
  etcd:
    addr: 192.168.71.69:2379
    dialTimeout: 1s
    readTimeout: 1s
    writeTimeout: 1s
  
